--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Xlennz/TraitParticle
build-by-default: true
branches:
- main
projects:
  TraitParticle:
    path: ""
    libs:
      - src: VennDev/LibVapmPMMP/LibVapmPMMP
        version: ^2.5.0
        branch: "main"
...
